server:
  port: 8084

# log相关配置
logging:
  config: classpath:logback-boot.xml

spring:
  application:
    name: jmqtt-test
  datasource:
    # mysql
#    url: ${RDB_URL:jdbc:mysql://dev.jmqtt.com:3366/jz_aj_player?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai}
#    username: ${RDB_USERNAME:root}
#    password: ${RDB_PASSWORD:zhibo2022}
#    driver-class-name: com.mysql.cj.jdbc.Driver
    # postgres
#    url: ${RDB_URL:jdbc:postgresql://dev.jmqtt.com:5432/zb_iot}
#    username: ${RDB_USERNAME:postgres}
#    password: ${RDB_PASSWORD:123456}
#    driver-class-name: org.postgresql.Driver
    # oracle
    url: ${RDB_URL:jdbc:oracle:thin:@odb.jmqtt.com:1521:helowin}
    username: ${RDB_USERNAME:zhibo}
    password: ${RDB_PASSWORD:zhibo2023}
    driverClassName: oracle.jdbc.driver.OracleDriver
  redis:
    host: ${REDIS_HOST:dev.jmqtt.com}
    port: ${REDIS_PORT:56379}
    password: ${REDIS_PASSWORD:zhibo2022}
    database: 11
    jedis:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 20
        min-idle: 0
    timeout: 30000

jmqtt:
  broker:
    # 是否开启匿名访问、默认登录账号、默认登录密码，可通过重写AuthValid来校验登录
    anonymous-enable: true
    user: admin
    pwd: 123456
    mqtt5:
      # 是否使用服务端心跳周期
      use-server-keepalive: false
      default-keepalive: 15
      # 服务端能同时处理的非qos0最大消息数，默认int最大值
      receive-maximum: 100
      # 服务端能处理的最大packet长度，默认256M，也是mqtt报文数据最大长度（可变头 + payload）
      maximum-packet-size: 20000
      # 主题别名最大值
      topic-alias-maximum: 1024
      # 服务端生成的clientId前缀，当客户端未设置clientId时，由服务端生成clientId返回
      client-id-prefix: JMQTT_CLIENT_
      # 可选的服务端功能，通配符订阅、订阅标识符、共享订阅、保留消息、最大qos等级
      wildcard-subscription-available: true
      subscription-identifier-available: true
      shared-subscription-available: true
      retain-available: true
      maximum-qos: 2
    # 是否开启高性能模式，开启则使用内存缓存QOS1、2的过程消息
    high-performance: true
    # 数据存储仓库，默认mem为内存存储，可选redis、rdb，配置redis需要配置redis连接，配置rdb需要数据库连接
    store: rdb
    # 默认值true
    # store = rdb条件下，useDefaultRdb为true时，优先使用依赖方数据源，依赖方没有数据源使用rdb配置的数据源
    # useDefaultRdb为false时，使用rdb配置的数据源
    # useDefaultRdb、rdb配置缺省时，使用依赖方数据源，依赖方无数据源则启动报错
    useDefaultRdb: false
    rdb:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rdb.jmqtt.com:3306/jmqtt?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: zhibo@2020
    # redis数据源，逻辑同rdb
    useDefaultRedis: false
    redis:
      redis-host: rdb.jmqtt.com
      redis-port: 56379
      redis-password: zhibo@2020
      database: 11
      max-wait-mills: 60000
      max-idle: 50
      min-idle: 20
      max-total: 200
    netty:
      tcp-port: 1883
      ssl-tcp-port: 1884
      websocket-port: 8883
      ssl-websocket-port: 8884
      ssl-key-store-type: PKCS12
      ssl-key-file-path: conf/server.pfx
      ssl-manager-pwd: 654321
      ssl-store-pwd: 654321
      use-epoll: true
      pooled-byte-buf-allocator-enable: true
    akka:
      # 是否开启Akka，开启后提高吞吐，集群环境下建议开启
      # Akka作用是将一个broker节点的消息同步到其他broker节点
      # 集群环境下，store为mem时，Akka必须开启
      enable: false
      # 当前Akka集群系统名称
      system-name: JMqttDispatcherSystem
      # 当前节点在集群中的ip和端口
      host: 127.0.0.1
      port: 25251
      # akka集群中所有节点，可以只配置集群中任意非当前节点。
      cluster-nodes:
        - 127.0.0.1:25251
#        - 127.0.0.1:25252
#        - 127.0.0.1:25253

