
-- ----------------------------
-- Table structure for JMQTT_EVENT
-- ----------------------------
CREATE TABLE "JMQTT_EVENT" (
                               "ID" NUMBER(20,0) NOT NULL,
                               "CONTENT" NCLOB NOT NULL,
                               "GMT_CREATE" NUMBER(20,0) NOT NULL,
                               "JMQTT_IP" NVARCHAR2(24) NOT NULL,
                               "EVENT_CODE" NUMBER(11,0) NOT NULL
);
COMMENT ON COLUMN "JMQTT_EVENT"."ID" IS '主键：也是集群节点批量拉消息的offset';
COMMENT ON COLUMN "JMQTT_EVENT"."CONTENT" IS '消息体';
COMMENT ON COLUMN "JMQTT_EVENT"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "JMQTT_EVENT"."JMQTT_IP" IS 'jmqtt服务器ip，发送该消息到集群中的broker ip';
COMMENT ON COLUMN "JMQTT_EVENT"."EVENT_CODE" IS '事件码';
COMMENT ON TABLE "JMQTT_EVENT" IS 'jmqtt 集群事件转发表：由发送端将消息发送到该表中，其他节点批量拉取该表中的事件进行处理';

-- ----------------------------
-- Table structure for JMQTT_INFLOW_MESSAGE
-- ----------------------------
CREATE TABLE "JMQTT_INFLOW_MESSAGE" (
                                        "ID" NUMBER(20,0) NOT NULL,
                                        "CLIENT_ID" NVARCHAR2(64) NOT NULL,
                                        "MSG_ID" NUMBER(11,0) NOT NULL,
                                        "CONTENT" NCLOB NOT NULL,
                                        "GMT_CREATE" NUMBER(20,0) NOT NULL
);
COMMENT ON COLUMN "JMQTT_INFLOW_MESSAGE"."ID" IS '主键id';
COMMENT ON COLUMN "JMQTT_INFLOW_MESSAGE"."CLIENT_ID" IS '设备id';
COMMENT ON COLUMN "JMQTT_INFLOW_MESSAGE"."MSG_ID" IS '消息id';
COMMENT ON COLUMN "JMQTT_INFLOW_MESSAGE"."CONTENT" IS '消息体内容';
COMMENT ON COLUMN "JMQTT_INFLOW_MESSAGE"."GMT_CREATE" IS '消息保存时间（对应消息接收时间）';
COMMENT ON TABLE "JMQTT_INFLOW_MESSAGE" IS '入栈消息表';

-- ----------------------------
-- Table structure for JMQTT_OFFLINE_MESSAGE
-- ----------------------------
CREATE TABLE "JMQTT_OFFLINE_MESSAGE" (
                                         "ID" NUMBER(20,0) NOT NULL,
                                         "CLIENT_ID" NVARCHAR2(64) NOT NULL,
                                         "CONTENT" NCLOB NOT NULL,
                                         "GMT_CREATE" NUMBER(20,0) NOT NULL
);
COMMENT ON COLUMN "JMQTT_OFFLINE_MESSAGE"."CLIENT_ID" IS '客户端id';
COMMENT ON COLUMN "JMQTT_OFFLINE_MESSAGE"."CONTENT" IS '消息体';
COMMENT ON COLUMN "JMQTT_OFFLINE_MESSAGE"."GMT_CREATE" IS '创建时间';
COMMENT ON TABLE "JMQTT_OFFLINE_MESSAGE" IS '离线消息表';

-- ----------------------------
-- Table structure for JMQTT_OUTFLOW_MESSAGE
-- ----------------------------
CREATE TABLE "JMQTT_OUTFLOW_MESSAGE" (
                                         "ID" NUMBER(20,0) NOT NULL,
                                         "CLIENT_ID" NVARCHAR2(64) NOT NULL,
                                         "MSG_ID" NUMBER(11,0) NOT NULL,
                                         "CONTENT" NCLOB NOT NULL,
                                         "GMT_CREATE" NUMBER(20,0) NOT NULL
);
COMMENT ON COLUMN "JMQTT_OUTFLOW_MESSAGE"."ID" IS '主键';
COMMENT ON COLUMN "JMQTT_OUTFLOW_MESSAGE"."CLIENT_ID" IS '目标客户端id';
COMMENT ON COLUMN "JMQTT_OUTFLOW_MESSAGE"."MSG_ID" IS '消息id';
COMMENT ON COLUMN "JMQTT_OUTFLOW_MESSAGE"."CONTENT" IS '消息内容';
COMMENT ON COLUMN "JMQTT_OUTFLOW_MESSAGE"."GMT_CREATE" IS '消息缓存时间';
COMMENT ON TABLE "JMQTT_OUTFLOW_MESSAGE" IS '出栈消息表';

-- ----------------------------
-- Table structure for JMQTT_OUTFLOW_SEC_MESSAGE
-- ----------------------------
CREATE TABLE "JMQTT_OUTFLOW_SEC_MESSAGE" (
                                             "ID" NUMBER(20,0) NOT NULL,
                                             "CLIENT_ID" NVARCHAR2(64) NOT NULL,
                                             "MSG_ID" NUMBER(11,0) NOT NULL,
                                             "GMT_CREATE" NUMBER(20,0) NOT NULL
);
COMMENT ON COLUMN "JMQTT_OUTFLOW_SEC_MESSAGE"."ID" IS '主键';
COMMENT ON COLUMN "JMQTT_OUTFLOW_SEC_MESSAGE"."CLIENT_ID" IS '目标客户端id';
COMMENT ON COLUMN "JMQTT_OUTFLOW_SEC_MESSAGE"."MSG_ID" IS '消息id';
COMMENT ON COLUMN "JMQTT_OUTFLOW_SEC_MESSAGE"."GMT_CREATE" IS '消息缓存时间';
COMMENT ON TABLE "JMQTT_OUTFLOW_SEC_MESSAGE" IS '发送qos2消息后的第二阶段的消息缓存表：接收pubRec后保留clientId，msgId等报文。设备重连时候进行重发';

-- ----------------------------
-- Table structure for JMQTT_RETAIN_MESSAGE
-- ----------------------------
CREATE TABLE "JMQTT_RETAIN_MESSAGE" (
                                        "ID" NUMBER(20,0) NOT NULL,
                                        "TOPIC" NVARCHAR2(128) NOT NULL,
                                        "CONTENT" NCLOB NOT NULL
);
COMMENT ON COLUMN "JMQTT_RETAIN_MESSAGE"."ID" IS '主键';
COMMENT ON COLUMN "JMQTT_RETAIN_MESSAGE"."TOPIC" IS '所属topic';
COMMENT ON COLUMN "JMQTT_RETAIN_MESSAGE"."CONTENT" IS '消息体';
COMMENT ON TABLE "JMQTT_RETAIN_MESSAGE" IS '保留消息表';

-- ----------------------------
-- Table structure for JMQTT_SESSION
-- ----------------------------
CREATE TABLE "JMQTT_SESSION" (
                                 "ID" NUMBER(20,0) NOT NULL,
                                 "CLIENT_ID" NVARCHAR2(64) NOT NULL,
                                 "STATE" NVARCHAR2(12) NOT NULL,
                                 "OFFLINE_TIME" NUMBER(20,0)
);
COMMENT ON COLUMN "JMQTT_SESSION"."ID" IS '主键';
COMMENT ON COLUMN "JMQTT_SESSION"."CLIENT_ID" IS '客户端id';
COMMENT ON COLUMN "JMQTT_SESSION"."STATE" IS '状态：ONLINE,OFFLINE两种';
COMMENT ON COLUMN "JMQTT_SESSION"."OFFLINE_TIME" IS 'OFFLINE状态时对应的离线时间戳（只有cleanStart为0时候离线才有该数据）';
COMMENT ON TABLE "JMQTT_SESSION" IS '客户端会话状态';

-- ----------------------------
-- Table structure for JMQTT_SUBSCRIPTION
-- ----------------------------
CREATE TABLE "JMQTT_SUBSCRIPTION" (
                                      "ID" NUMBER(20,0) NOT NULL,
                                      "CLIENT_ID" NVARCHAR2(64) NOT NULL,
                                      "TOPIC" NVARCHAR2(128) NOT NULL,
                                      "QOS" NUMBER(4,0) NOT NULL
);
COMMENT ON COLUMN "JMQTT_SUBSCRIPTION"."ID" IS '主键';
COMMENT ON COLUMN "JMQTT_SUBSCRIPTION"."CLIENT_ID" IS '客户端id';
COMMENT ON COLUMN "JMQTT_SUBSCRIPTION"."TOPIC" IS '订阅的topic';
COMMENT ON COLUMN "JMQTT_SUBSCRIPTION"."QOS" IS '对应的qos';
COMMENT ON TABLE "JMQTT_SUBSCRIPTION" IS '客户端订阅关系';

-- ----------------------------
-- Table structure for JMQTT_WILL_MESSAGE
-- ----------------------------
CREATE TABLE "JMQTT_WILL_MESSAGE" (
                                      "ID" NUMBER(20,0) NOT NULL,
                                      "CLIENT_ID" NVARCHAR2(64) NOT NULL,
                                      "CONTENT" NCLOB NOT NULL,
                                      "GMT_CREATE" NUMBER(20,0) NOT NULL
);
COMMENT ON COLUMN "JMQTT_WILL_MESSAGE"."CLIENT_ID" IS '客户端id';
COMMENT ON COLUMN "JMQTT_WILL_MESSAGE"."CONTENT" IS '消息体';
COMMENT ON COLUMN "JMQTT_WILL_MESSAGE"."GMT_CREATE" IS '创建时间';
COMMENT ON TABLE "JMQTT_WILL_MESSAGE" IS '遗嘱消息表';

-- ----------------------------
-- Checks structure for table JMQTT_EVENT
-- ----------------------------
ALTER TABLE "JMQTT_EVENT" ADD CONSTRAINT "SYS_C0011141" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_EVENT" ADD CONSTRAINT "SYS_C0011142" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_EVENT" ADD CONSTRAINT "SYS_C0011143" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_EVENT" ADD CONSTRAINT "SYS_C0011144" CHECK ("jmqtt_ip" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_EVENT" ADD CONSTRAINT "SYS_C0011145" CHECK ("event_code" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JMQTT_INFLOW_MESSAGE
-- ----------------------------
ALTER TABLE "JMQTT_INFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011165" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JMQTT_INFLOW_MESSAGE
-- ----------------------------
ALTER TABLE "JMQTT_INFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011131" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_INFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011132" CHECK ("CLIENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_INFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011133" CHECK ("MSG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_INFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011134" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_INFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011135" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table JMQTT_INFLOW_MESSAGE
-- ----------------------------
CREATE INDEX "IDX_CLIENT_ID_INFLOW"
    ON "JMQTT_INFLOW_MESSAGE" ("CLIENT_ID" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE UNIQUE INDEX "UQE_CLIENT_ID_MSG_ID_INFLOW"
    ON "JMQTT_INFLOW_MESSAGE" ("CLIENT_ID" ASC, "MSG_ID" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Primary Key structure for table JMQTT_OFFLINE_MESSAGE
-- ----------------------------
ALTER TABLE "JMQTT_OFFLINE_MESSAGE" ADD CONSTRAINT "SYS_C0011164" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JMQTT_OFFLINE_MESSAGE
-- ----------------------------
ALTER TABLE "JMQTT_OFFLINE_MESSAGE" ADD CONSTRAINT "SYS_C0011127" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_OFFLINE_MESSAGE" ADD CONSTRAINT "SYS_C0011128" CHECK ("CLIENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_OFFLINE_MESSAGE" ADD CONSTRAINT "SYS_C0011129" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_OFFLINE_MESSAGE" ADD CONSTRAINT "SYS_C0011130" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table JMQTT_OFFLINE_MESSAGE
-- ----------------------------
CREATE INDEX "IDX_CLIENT_ID_OFFLINE"
    ON "JMQTT_OFFLINE_MESSAGE" ("CLIENT_ID" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE INDEX "IDX_GMT_CREATE_OFFLINE"
    ON "JMQTT_OFFLINE_MESSAGE" ("GMT_CREATE" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Checks structure for table JMQTT_OUTFLOW_MESSAGE
-- ----------------------------
ALTER TABLE "JMQTT_OUTFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011136" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_OUTFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011137" CHECK ("CLIENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_OUTFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011138" CHECK ("MSG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_OUTFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011139" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_OUTFLOW_MESSAGE" ADD CONSTRAINT "SYS_C0011140" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table JMQTT_OUTFLOW_MESSAGE
-- ----------------------------
CREATE INDEX "IDX_CLIENT_ID_OUTFLOW"
    ON "JMQTT_OUTFLOW_MESSAGE" ("CLIENT_ID" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE UNIQUE INDEX "UQE_CLIENT_ID_MSG_ID_OUTFLOW"
    ON "JMQTT_OUTFLOW_MESSAGE" ("MSG_ID" ASC, "CLIENT_ID" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Checks structure for table JMQTT_OUTFLOW_SEC_MESSAGE
-- ----------------------------
ALTER TABLE "JMQTT_OUTFLOW_SEC_MESSAGE" ADD CONSTRAINT "SYS_C0011146" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_OUTFLOW_SEC_MESSAGE" ADD CONSTRAINT "SYS_C0011147" CHECK ("CLIENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_OUTFLOW_SEC_MESSAGE" ADD CONSTRAINT "SYS_C0011148" CHECK ("MSG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_OUTFLOW_SEC_MESSAGE" ADD CONSTRAINT "SYS_C0011149" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table JMQTT_OUTFLOW_SEC_MESSAGE
-- ----------------------------
CREATE INDEX "IDX_CLIENT_ID_SEC"
    ON "JMQTT_OUTFLOW_SEC_MESSAGE" ("CLIENT_ID" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
CREATE UNIQUE INDEX "UQE_CLIENT_ID_MSG_ID_SEC"
    ON "JMQTT_OUTFLOW_SEC_MESSAGE" ("CLIENT_ID" ASC, "MSG_ID" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Checks structure for table JMQTT_RETAIN_MESSAGE
-- ----------------------------
ALTER TABLE "JMQTT_RETAIN_MESSAGE" ADD CONSTRAINT "SYS_C0011150" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_RETAIN_MESSAGE" ADD CONSTRAINT "SYS_C0011151" CHECK ("TOPIC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_RETAIN_MESSAGE" ADD CONSTRAINT "SYS_C0011152" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
CREATE UNIQUE INDEX "UQE_TOPIC_RETAIN" ON "JMQTT_RETAIN_MESSAGE" ("TOPIC")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS";

-- ----------------------------
-- Checks structure for table JMQTT_SESSION
-- ----------------------------
ALTER TABLE "JMQTT_SESSION" ADD CONSTRAINT "SYS_C0011153" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_SESSION" ADD CONSTRAINT "SYS_C0011154" CHECK ("CLIENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_SESSION" ADD CONSTRAINT "SYS_C0011155" CHECK ("STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table JMQTT_SESSION
-- ----------------------------
CREATE UNIQUE INDEX "UQE_CLIENT_ID_SESSION"
    ON "JMQTT_SESSION" ("CLIENT_ID" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Checks structure for table JMQTT_SUBSCRIPTION
-- ----------------------------
ALTER TABLE "JMQTT_SUBSCRIPTION" ADD CONSTRAINT "SYS_C0011156" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_SUBSCRIPTION" ADD CONSTRAINT "SYS_C0011157" CHECK ("CLIENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_SUBSCRIPTION" ADD CONSTRAINT "SYS_C0011158" CHECK ("TOPIC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_SUBSCRIPTION" ADD CONSTRAINT "SYS_C0011159" CHECK ("QOS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table JMQTT_SUBSCRIPTION
-- ----------------------------
CREATE INDEX "IDX_CLIENT_ID_SUB"
    ON "JMQTT_SUBSCRIPTION" ("CLIENT_ID" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
CREATE INDEX "IDX_TOPIC_SUB"
    ON "JMQTT_SUBSCRIPTION" ("TOPIC" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

-- ----------------------------
-- Checks structure for table JMQTT_WILL_MESSAGE
-- ----------------------------
ALTER TABLE "JMQTT_WILL_MESSAGE" ADD CONSTRAINT "SYS_C0011160" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_WILL_MESSAGE" ADD CONSTRAINT "SYS_C0011161" CHECK ("CLIENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_WILL_MESSAGE" ADD CONSTRAINT "SYS_C0011162" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JMQTT_WILL_MESSAGE" ADD CONSTRAINT "SYS_C0011163" CHECK ("GMT_CREATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table JMQTT_WILL_MESSAGE
-- ----------------------------
CREATE UNIQUE INDEX "UQE_CLIENT_ID_WILL"
    ON "JMQTT_WILL_MESSAGE" ("CLIENT_ID" ASC)
    LOGGING
  TABLESPACE "USERS"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
);
